version: '{build}'
shallow_clone: true

environment:
  matrix:
    - perl_type: system
    - perl_type: strawberry
    - perl_type: cygwin

install:
  - 'call appveyor.cmd perl_setup'
  - '%perl% -V'
  - '%cpanm% -n Dist::Zilla'
  - 'dzil authordeps --missing | cpanm -n'
  - 'dzil listdeps --missing | cpanm -n'

build: off

test_script:
  - dzil test -v
